secret: dongtaiwang.com
mixed-port: 7890
allow-lan: false
log-level: info
dns:
  enabled: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
- name: dongtaiwang.com_0                     
  type: vmess
  server: 104.19.55.52                      
  port: 443                                     
  uuid: 7f1ffa3d-105b-43b0-a458-425780fa9938       
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  servername: afternoon-friend-volkswagen-mentor.trycloudflare.com                    
  ws-opts:
    path: "7f1ffa3d-105b-43b0-a458-425780fa9938-vm"                             
    headers:
      Host: afternoon-friend-volkswagen-mentor.trycloudflare.com

- name: dongtaiwang.com_1                    
  type: vmess
  server: 162.159.136.22                   
  port: 8880                                     
  uuid: 7f1ffa3d-105b-43b0-a458-425780fa9938       
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: afternoon-friend-volkswagen-mentor.trycloudflare.com                    
  ws-opts:
    path: "7f1ffa3d-105b-43b0-a458-425780fa9938-vm"                             
    headers:
      Host: afternoon-friend-volkswagen-mentor.trycloudflare.com 

- name: dongtaiwang.com_2
  type: vmess
  server: 172.64.144.114               
  port: 8443                                     
  uuid: 7f1ffa3d-105b-43b0-a458-425780fa9938       
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  servername: afternoon-friend-volkswagen-mentor.trycloudflare.com                    
  ws-opts:
    path: "7f1ffa3d-105b-43b0-a458-425780fa9938-vm"                             
    headers:
      Host: afternoon-friend-volkswagen-mentor.trycloudflare.com

- name: dongtaiwang.com_3           
  type: vmess
  server: 104.19.38.66                
  port: 8880                                     
  uuid: 7f1ffa3d-105b-43b0-a458-425780fa9938       
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: afternoon-friend-volkswagen-mentor.trycloudflare.com                    
  ws-opts:
    path: "7f1ffa3d-105b-43b0-a458-425780fa9938-vm"                             
    headers:
      Host: afternoon-friend-volkswagen-mentor.trycloudflare.com 


proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - DIRECT
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
  - name: ♻️ 自动选择
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
  - name: 📲 电报信息
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - ♻️ 自动选择
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
rules:
  - MATCH,🚀 节点选择
